name: pull request comment

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  SayHello:
    if: ${{ github.event.issue.pull_request }}    # <--- The other way to compare if it's on a PR or on an issue
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name
      - name: run e2e
        if: contains(github.event.comment.body, '/run-e2e')
        run: |
          echo running e2e
