name: pull request comment

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  SayHello:
    if: ${{ github.event.issue.pull_request }}    # <--- The other way to compare if it's on a PR or on an issue
    runs-on: [ubuntu-latest]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: run e2e
        if: contains(github.event.comment.body, '/run-e2e')
        run: |
          echo running e2e
